FROM golang:1.23-alpine AS build
WORKDIR /src
COPY . .
RUN CGO_ENABLED=0 go build -o /out/queue-service ./cmd/queue-service

FROM gcr.io/distroless/base-debian12:nonroot
WORKDIR /
COPY --from=build /out/queue-service /queue-service
EXPOSE 8080
USER nonroot:nonroot
ENTRYPOINT ["/queue-service","-addr=:8080"]
