networks:
  default:
    driver: bridge

services:
  queue:
    build:
      context: .
      dockerfile: Dockerfile.queue
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
  upload-service:
    build:
      context: .
      dockerfile: Dockerfile.upload-service
    ports:
      - "8081:8081"
    depends_on:
      - queue
    volumes:
      - ./data:/data
    command: ["-addr",":8081","-out","/data/output.txt","-queue-url","http://queue:8080","-queue","lines"]
