networks:
  default:
    driver: bridge

services:
  queue:
    build:
      context: .
      dockerfile: Dockerfile.queue
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    depends_on:
      - queue
    volumes:
      - ./data:/data
    command: ["-queue-url","http://queue:8080","-queue","lines","-watch-dir","/data/in","-watch-out","/data/out"]
