FROM golang:1.23-alpine AS build
WORKDIR /src
COPY . .
RUN CGO_ENABLED=0 go build -o /out/upload-service ./cmd/upload-service

FROM gcr.io/distroless/base-debian12:nonroot
WORKDIR /
COPY --from=build /out/upload-service /upload-service
USER nonroot:nonroot
ENTRYPOINT ["/upload-service"]
